# Generated by Django 4.1.1 on 2022-09-17 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profie',
            new_name='Profile',
        ),
    ]
